version: '3.8'

services:
  python_daemon:
    build: .
    container_name: python_daemon_container
    ports:
      - "9001:9001"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=notifications_db
      - DB_HOST=mysql
      - DB_PORT=3306
      - SMTP_SERVER=email-smtp.us-east-1.amazonaws.com
      - SMTP_PORT=587
      - SMTP_USERNAME=your_ses_smtp_username
      - SMTP_PASSWORD=your_ses_smtp_password
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your_aws_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_aws_secret_access_key
    volumes:
      - .:/app
    depends_on:
      - mysql
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notifications_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: